### ISSUE TITLE
Compliance: General Data Protection Regulation

### ISSUE THREAD

**Issue by sairope** [lilili87222/Admob-ANE#4]
Are you going to update this native extension once Google releases a new SDK that provides a consent gathering tool? Without the ability to ask users for consent, we won't be able to display admob ads in Europe. The new EU regulation will apply on 25th of may 2018.

Here you can find more info:
support.google.com/admob/answer/7666366

**Comment by lilili87222** [comment]
Yes,sdk will been updated .

**Comment by Gusher** [comment]
Any news on this issue? Has it been updated? Resolved?

**Comment by lilili87222** [comment]
extraParam=new ExtraParameter();
	//extraParam.testDeviceID="true";
//	extraParam.isChildApp=true;//if is tagForChildDirectedTreatment,set true
   //     extraParam.isDesignedForFamilies=true;
        extraParam.nonPersonalizedAds=true;//if want to load non Personalized ads set true
	Admob.getInstance().showBanner(AdmobSize.BANNER_320x50,AdmobPosition.BOTTOM_CENTER,80,extraParam);
